// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fceycljahmdordqnjfmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjZXljbGphaG1kb3JkcW5qZm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDgyNzAsImV4cCI6MjA3MDMyNDI3MH0.hWalWfjprkmv66Ba8g_UTfa-OzBH27f-DYWBS6IDqd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});